### ISSUE TITLE
<label> under <ul>

### ISSUE THREAD

**Issue by masciugo** [RSSchermer/ember-multiselect-checkboxes#10]
Unlike the demo my canonical usage doesn't produce `<li>` tags under `<ul>` but directly `<label>`. Am I missing anything?

**Comment by RSSchermer** [comment]
Hey, thanks a lot for finding this bug! 

It seems this snuck in during the 0.3 refactor. I just published 0.3.2 which should fix this.

**Comment by masciugo** [comment]
thank you... it works. It would actually be great to let users provide class for `<ul>` and `<li>` to use with bootstrap for example. Can you suggest any alternative way?

**Comment by RSSchermer** [comment]
Setting a class on the `<ul>` is straightforward, simply set the class attribute on the multiselect-checkboxes component:

```scala
{{multiselect-checkboxes class="some-class" ... }}
```

Its not yet possible to customize the `<li>` elements, but I'm working on a new release that will you to pass a custom template block that will be used for each option:

```scala
{{#multiselect-checkboxes options=persons selection=selectedPersons labelProperty="name" as |label isSelected|}}
  <li class="some-class">
    <label>
      {{input type="checkbox" checked=isSelected}}
      {{label}}
    </label>
  </li>
{{/multiselect-checkboxes}}
```

I've spent a little time working on this over the weekend and have it working when testing it manually. Unfortunately Ember 1.13 seems to break the automated tests though. I should get around to fixing those some time this week and then I'll publish it as 0.4.0.

**Comment by masciugo** [comment]
Sounds great, thanks a lot
