### ISSUE TITLE
Yielding template does not seem to work

### ISSUE THREAD

**Issue by anthonycollini** [RSSchermer/ember-multiselect-checkboxes#11]
When I yield a template to the component, ie.
```
{{#multiselect-checkboxes options=users labelProperty='name' selection=selectedUsers as |label isSelected|}}
  <li>
    <label>
      {{input type="checkbox" checked=isSelected}}
      {{label}}
    </label>
  </li>
{{/multiselect-checkboxes}}
```

It seems to disregard the template I put inside the tags. It still shows the default checkboxes, even if I remove the yielded template:

```
{{#multiselect-checkboxes options=users labelProperty='name' selection=selectedUsers as |label isSelected|}}
{{/multiselect-checkboxes}}
```

Or try to switch any of the content inside, for instance, adding an h1, or passing the label to a handlebars helper, etc.

Thoughts to why this would be happening?

**Comment by RSSchermer** [comment]
What Ember version and version of ember-multiselect-checkboxes are you using?

**Comment by anthonycollini** [comment]
```"ember-multiselect-checkboxes": "^0.4.0"```
```"ember-cli": "^0.2.7",```
```"ember": "1.12.0",```

**Comment by RSSchermer** [comment]
Ah right, then I think Ember 1.12 is the problem. The custom templates depend on Ember features that are still behind feature flags in 1.12. If upgrading to 1.13 is not desirable right now, you could try setting the `ember-views-component-block-info` feature flag to true.

I should perhaps update the readme to mention that the custom templates require 1.13.

**Comment by oswaldoacauan** [comment]
Same issue here.
`Ember             : 1.12.0` with 'ember-views-component-block-info': true`.

Doesn't seems to work even with the feature enabled.

**Comment by anthonycollini** [comment]
Upgrading worked for me.

**Comment by oswaldoacauan** [comment]
Problably upgrading will work for me to, but i can do it on the project right now.
