### ISSUE TITLE
Cannot combine select all/none action with selected checkboxes

### ISSUE THREAD

**Issue by masciugo** [RSSchermer/ember-multiselect-checkboxes#13]
I am using the component this way

    {{#multiselect-checkboxes options=allPlayers labelProperty='name' selection=purchase.players class="list-group" as |label isSelected|}}
      <li class="list-group-item">
        <label>
          {{input type="checkbox" checked=isSelected}}
          {{label}}
        </label>
      </li>
    {{/multiselect-checkboxes}}

In order to select all/none players for a purchase I added two button which lead to this action:

    selectAllTogether: function (arg) {
      var purchase = this.get('purchase');
      switch(arg) {
        case 'all':
            purchase.set('players', this.get('allPlayers'));
            break;
        case 'none':
            purchase.get('players').clear();
            break;
        default:
            break;
      }
    },

which works correctly behind the scenes but checkboxes do not get updated all together

**Comment by RSSchermer** [comment]
Before I dive into testing your case myself, could you try:

```
...
case 'all':
   purchase.set('players', this.get('allPlayers').copy());
   break;
...
```

Note, that it adds `.copy()`, because you don't want your "selection" array to be the "all" array, because then your "all" gets updated. You want it to be a different array that just happens to hold the same objects as the "all" array.

I'm not 100% sure this is causing your issue, but this is the first thing that comes to mind. If this doesn't work I'll try to replicate and figure it out.

**Comment by masciugo** [comment]
hi and thanks for your time. I'm using ember 2.0.1 and there is not a `.copy()` method for `ManyArray` object. 
However it used to work before I started building e second version (ember 2, ember-multiselect-checkboxes 0.4.2 etc.) of [my small webapp](https://github.com/masciugo/quenta/tree/with-backend). And, yes I used the "all" array directly. [Here](https://github.com/masciugo/quenta/blob/with-backend/app/components/purchase-form.js) is the component wher I use your lib along with its [template](https://github.com/masciugo/quenta/blob/with-backend/app/templates/components/purchase-form.hbs) if you ever need more information. 

The following is a gif that the unexpected behaviour:
![all-none](https://cloud.githubusercontent.com/assets/454321/9784851/43ee04b4-57ae-11e5-99e9-f4a647a4d0fa.gif)

While an old working version of the application is [here](http://polar-shore-3415.herokuapp.com/) and its the code is on the master branch.

**Comment by RSSchermer** [comment]
Thanks very much for the detailed report. The copy method indeed seems to have been removed from Ember collections (which I find kind of puzzling, and I kind find when they were deprecated and removed). 

Select all and select none functionality is definitely something I intend to possible with ember-multiselect-checkboxes. I'll try and get to the bottom of this, although that might have to wait till the weekend.

**Comment by RSSchermer** [comment]
I did some testing and I think this might work

```js
...
case 'all':
  purchase.set('players', this.get('allPlayers').copy());
  break;
...
```

It replaces Ember's `copy` with the natice js `slice`. I haven't tested it on your `with-backend` branch, because then I'd have to set up your backend API as well, but it seems to work on your `master` branch and also on the test page in the dummy application on this repo (see [this controller](https://github.com/RSSchermer/ember-multiselect-checkboxes/blob/0.4.3/tests/dummy/app/controllers/ember-objects-test.js)).

Let me know if this works.

**Comment by masciugo** [comment]
Sorry If I reply so late and thanks. I give it a quick try just replacing the method. It does not give any error but it does not solve. I'll try better again tomorrow but maybe is worth to mention that my *players* property is an hasMany association ...

**Comment by masciugo** [comment]
ok the following works:

    noneSelected: Ember.computed.empty('selectedPlayers'),
    noPayer: Ember.computed.empty('purchase.payer.id'),
    allPlayers: Ember.computed.readOnly('purchase.ledger.players'),

    selectedPlayers: Ember.computed('purchase.players', function (k,v) {
      return Ember.A(this.get('purchase.players').slice());
    }),

    allSelected: Ember.computed('selectedPlayers.length', function () {
      return this.get('selectedPlayers.length') === this.get('allPlayers.length');
    }),

    actions: {
      selectAllTogether: function (arg) {
        var purchase = this.get('purchase');
        switch(arg) {
          case 'all':
              this.set('selectedPlayers', Ember.A(this.get('allPlayers').slice()));
              break;
          case 'none':
              this.set('selectedPlayers',Ember.A());
              break;
          default:
              break;
        };
      },
      submit: function(purchase) {
        purchase.set('players', this.get('selectedPlayers'));
        this.sendAction('submit',purchase);
      },

but I don't well understand `Ember.A()` and `.slice()` used together as It seems from the doc that they do the same: create a new array from another one without altering it. 

Thanks for your help and for your possible explanation..

**Comment by RSSchermer** [comment]
Are Ember prototype extensions enabled? 

It is my understanding that wrapping a native array in `Ember.A` is only necessary if they are disabled. If they are disabled though, this solution makes sense and might be related to #14.

**Comment by masciugo** [comment]
No they are enabled..  
Anyway I must go ahead. thanks a lot
