### ISSUE TITLE
Showing a checked item from an array of objects

### ISSUE THREAD

**Issue by vikram-s-narayan** [RSSchermer/ember-multiselect-checkboxes#15]
I'm able to show an item as checked (selected) if it is a plain javascript array like this: 

Controller: 
```
export default Ember.Controller.extend({`
      selectedLetters: ['a'],
      lettersArray: ['a','b','c'],
    });
```
    
Template: 
`{{multiselect-checkboxes options=lettersArray selection=selectedLetters}}`

However, I'm unable to show an item as checked when I have to deal with an array of objects: 

Controller: 
```
    export default Ember.Controller.extend({
        selectedLetters: [{letterId: 1, letter: 'a'}], //I'd like to have this as a pre-selected item
        lettersArray: [{letterId: 1, letter: 'a'},{letterId: 1, letter: 'b'},{letterId: 1, letter: 'c'}],
    });
```
Template: 
    `{{multiselect-checkboxes options=lettersArray labelProperty='letter' selection=selectedLetters}}`

----
Am I missing something here? Can you please help?

**Comment by RSSchermer** [comment]
What version of ember are you using?

**Comment by vikram-s-narayan** [comment]
thanks for the quick response. I'm using Ember 1.13.7

**Comment by RSSchermer** [comment]
Thanks, I'll try to reproduce and fix over the next few days.

**Comment by vikram-s-narayan** [comment]
okay ... thank you very much.

**Comment by RSSchermer** [comment]
Ok, so I've figured out whats going on and actually it makes perfect sense. 

If you compare two objects in javascript for equality, javascript checks if the pointers are the same, not if the object's fields are all equal:

```js
var objectOne = {a: 1, b: 2};
var objectTwo = {a: 1, b: 2};
var objectThree = objectOne;

console.log(objectOne === objectTwo); // false
console.log(objectOne == objectTwo); // also false

console.log(objectOne === objectThree); // true, same pointer
```

To check if an option should be selected, the component checks if the option is in the `selection` list, by comparing the option value to all values in the selection list. In the case of object comparison, that means the pointers have to be the same. I would consider this the intended behaviour, not a bug.

The following should work:

```js
var letterOne = {letterId: 1, letter: 'a'};
var letterTwo = {letterId: 2, letter: 'b'};
var letterThree = {letterId: 3, letter: 'c'};

export default Ember.Controller.extend({
  selectedLetters: [letterOne],
  lettersArray: [letterOne, letterTwo, letterThree],
});
```
Or, perhaps more convenient:

```js
var letters = [
  {letterId: 1, letter: 'a'},
  {letterId: 2, letter: 'b'},
  {letterId: 3, letter: 'c'}
];

export default Ember.Controller.extend({
  selectedLetters: [letters[0]],
  lettersArray: letters,
});
```

**Comment by vikram-s-narayan** [comment]
thank you for this.
