### ISSUE TITLE
Keyboard Navigation Is Lost Upon Check/Uncheck

### ISSUE THREAD

**Issue by nadnoslen** [RSSchermer/ember-multiselect-checkboxes#17]
First off, love the spirit of this addon.

With a list of checkboxes it is nice to navigate from one to the other pressing the `tab` key.  You can then check a focused checkbox with the `space` key.  Unfortunately focus is lost on the active checkbox once it has been checked/unchecked.  This puts the end user at the disadvantage of having to tab all the way back to the checkbox controls or use their mouse to click the items.

**Comment by RSSchermer** [comment]
This seems to work for me on the [demo](https://rsschermer.github.io/ember-multiselect-checkboxes/) on Chromium Version 47.0.2526.73 Ubuntu 15.10 (64-bit). The demo is based on an early version of this addon. Could you check if it works for you with the demo? If it does, that would probably help track down what's causing this.

**Comment by nadnoslen** [comment]
Hey @RSSchermer,
I can confirm that it does work perfectly on the demo.
I am working bleeding-edge with Ember-2.2, perhaps I've got an issue in that regard.  I'll do some more testing and get back to you.

**Comment by RSSchermer** [comment]
I've just tested with the latest version of the addon and Ember 2.0 and it does indeed not work for me either.

DOM structure looks as follows with latest version and Ember 2.0 in Chrome console:

```html
<ul id="ember442" class="ember-view multiselect-checkboxes">    
    <li>
      <label>
        <input id="ember468" type="checkbox" class="ember-view ember-checkbox">
        Lisa
      </label>
    </li>
    <li>
      <label>
        <input id="ember470" type="checkbox" class="ember-view ember-checkbox">
        Bob
      </label>
    </li>
    <li>
      <label>
        <input id="ember472" type="checkbox" class="ember-view ember-checkbox">
        John
      </label>
    </li>
</ul>
```

Versus this DOM structure in the demo:

```html
<ul id="ember327" class="ember-view multiselect-checkboxes">
  <script id="metamorph-3-start" type="text/x-placeholder"></script>
  <script id="metamorph-0-start" type="text/x-placeholder"></script>
  <li id="ember353" class="ember-view multiselect-checkbox-option">
    <label>
      <input id="ember356" class="ember-view ember-checkbox" type="checkbox">
      <script id="metamorph-4-start" type="text/x-placeholder"></script>
      apple
      <script id="metamorph-4-end" type="text/x-placeholder"></script>
    </label>
  </li>
  <script id="metamorph-0-end" type="text/x-placeholder"></script>
  <script id="metamorph-1-start" type="text/x-placeholder"></script>
  <li id="ember357" class="ember-view multiselect-checkbox-option">
    <label>
      <input id="ember358" class="ember-view ember-checkbox" type="checkbox">
      <script id="metamorph-5-start" type="text/x-placeholder"></script>
      banana
      <script id="metamorph-5-end" type="text/x-placeholder"></script>
    </label>
  </li>
  <script id="metamorph-1-end" type="text/x-placeholder"></script>
  <script id="metamorph-2-start" type="text/x-placeholder"></script>
  <li id="ember359" class="ember-view multiselect-checkbox-option">
    <label>
      <input id="ember360" class="ember-view ember-checkbox" type="checkbox">
      <script id="metamorph-6-start" type="text/x-placeholder"></script>
      orange
      <script id="metamorph-6-end" type="text/x-placeholder"></script>
    </label>
  </li>
  <script id="metamorph-2-end" type="text/x-placeholder"></script>
  <script id="metamorph-3-end" type="text/x-placeholder"></script>
</ul>
```

Apart from the metamorph tags that seems fairly equivalent to me; none of the differences in the DOM seem like they would cause chrome to get lost.

What might be happening here is that the newer version of ember redraws the checkbox when it gets checked, whereas the older version did not. That means the original checkbox input essentially gets replaced with an entirely new checkbox input, which would naturally not have focus.

It's probably worthwhile testing if this is a general issue with lists of checkboxes in the current version of Ember. If so I think it might be better to resolve this issue upstream. It's getting late here though so additional testing will have to wait till tomorrow.

**Comment by nadnoslen** [comment]
Yes, I can see the repaint of the checkbox in Ember-2.x.  It's most certainly the culprit :disappointed:

This does need some additional investigation.  I'll see if I can help.

**Comment by RSSchermer** [comment]
Issue #22 helped accidentally uncover the underlying problem for this issue as well. As of 0.6.1 this should be fixed.
