### ISSUE TITLE
Template Block Style: Pass Option Object To Loop Not Just Label And Value

### ISSUE THREAD

**Issue by nadnoslen** [RSSchermer/ember-multiselect-checkboxes#18]
Has anyone considered passing the checkbox individual object to the Template Block?  For example:

    {{#multiselect-checkboxes options=users selection=selectedUsers as | option isSelected |}}
      <li>
        <label>
          {{input type="checkbox" checked=isSelected}}
          {{option.label}} ({{option.value}})
        </label>
      </li>
    {{/multiselect-checkboxes}}

Why would you do this?  Perhaps you want the first checkbox item to be `autofocus=true`.  Your option object can implement a function named `isAutofocused` that returns a boolean.  Then your input could be look like this:

    ...
        <label>
          {{input type="checkbox" checked=isSelected autofocus=option.isAutofocused}}
          {{option.label}} ({{option.value}})
        </label>
    ...

**Comment by RSSchermer** [comment]
At first glance this does indeed seem like an elegant solution and I can't believe this hadn't occurred to me. I will attempt to implement and see if I run into unforeseen issues. If not then I think this is worth breaking BC for.

**Comment by RSSchermer** [comment]
Resolved as of version 0.6.0.

**Comment by nadnoslen** [comment]
:+1:
