### ISSUE TITLE
Documentation: Template Block, Avoiding <ul> Styling

### ISSUE THREAD

**Issue by nadnoslen** [RSSchermer/ember-multiselect-checkboxes#19]
If you want to avoid the `<ul>` styling that ships with the component, it might be beneficial to mention in the docs that you can clear the `tagName` property or set it to something else (e.g. a `div`).  For example:

    {{#multiselect-checkboxes tagName="div" options=users labelProperty='name' selection=selectedUsers as |label isSelected value|}}
    ...
    {{/multiselect-checkboxes}}

I realize that this is common knowledge if you are familiar with components, however some developers that are starting out could use this extra help.

**Comment by RSSchermer** [comment]
Agreed, wouldn't hurt to add this explicitly to the readme :+1: Will add this as part of next release.

**Comment by RSSchermer** [comment]
Resolved as of version 0.6.0.
