### ISSUE TITLE
All/None Helper

### ISSUE THREAD

**Issue by nadnoslen** [RSSchermer/ember-multiselect-checkboxes#20]
I saw #13 yesterday and was working on my own multi-checkbox challenge in my project (unfortunately I could not use this addon).  However my particular use case got me to thinking whether this addon could benefit from an `all` boolean property that is observed and will check-all or check-none based on `all`'s state.

For example: this would check-all users

    {{multiselect-checkboxes options=users selection=selectedUsers all=true}}

...and this would check all users based on a controller allNone property:

    {{multiselect-checkboxes options=users selection=selectedUsers all=allNone}}

Some implementation notes from my experience:
* The `all` property should be observed on init to ensure the state of the checkboxes is correct at load time.
* Always be judicious when observing multiple properties and leverage `Ember.run.once` to avoid accidentally introducing a race condition.  Sorry, I haven't looked deep enough in the code here to confirm if this implementation may suffer from this.
* The `all` state may need to be managed by the component.  For example, if someone manually un-checks every checkbox, and the `all` state was previously `true`, you may want to set `all` to false once the final checkbox is un-checked.  This also works in the other direction; user manually checks all checkboxes...  Hopefully that makes some sense?

**Comment by RSSchermer** [comment]
There's actually an example of select all/deselect all functionality in the dummy app for this addon's tests, see [this controller](https://github.com/RSSchermer/ember-multiselect-checkboxes/blob/0.6.0/tests/dummy/app/controllers/ember-objects-test.js) and [this template](https://github.com/RSSchermer/ember-multiselect-checkboxes/blob/0.6.0/tests/dummy/app/templates/ember-objects-test.hbs). This implementation essentially sets the selection to a copy of the options array for select all, and to an empty array for deselect all.

As you point out, doing select all/deselect all  via an attribute would probably involve the component managing the state of this property. I'm not sure if the additional complexity surrounding that would be worth it compared to the way this is implemented in the dummy app example.

**Comment by nadnoslen** [comment]
Sounds good to me.  I think the solution you cited is elegant enough.  Thanks for pointing that out, I just don't have time to vet everything before my ideas are forgotten.  Cheers :smiley:
