### ISSUE TITLE
Can't observe "selection" property

### ISSUE THREAD

**Issue by gte451f** [RSSchermer/ember-multiselect-checkboxes#21]
For some reason, I can't fire an action or observe changes to the multi select.  This pseudo code fails silently...

//controller.js
```javascript
// detect changes to selection property
activeChanged: Ember.observer('activeList', function () {
    console.log('activeList changed');
}),
activeList: [],
```

//template.hbs
```
        {{#multiselect-checkboxes options=allOptions selection=activeList as |field isSelected|}}
            <div class="checkbox">
                <label>
                    {{input type="checkbox" checked=isSelected}}
                    {{field}}
                </label>
            </div>
        {{/multiselect-checkboxes}}
```

I've seen other issues about passing an action but I couldn't figure out what I *should* be doing to fire actions or in the example above, observe changes to the list.....

**Comment by RSSchermer** [comment]
Could you try:

```js
activeChanged: Ember.observer('activeList.[]', function () {
    console.log('activeList changed');
})
```

The actual array object does not change when the selection is updated. Observing `'activeList'` only fires when the array object's identity changes. Observing `'arrayList.[]'` should also fire if the array object's contents change.

**Comment by gte451f** [comment]
That was it, many thanks!

**Comment by RSSchermer** [comment]
Glad I could help!
