### ISSUE TITLE
Very slow with many items

### ISSUE THREAD

**Issue by medokin** [RSSchermer/ember-multiselect-checkboxes#22]
Any Idea how to solve this?

**Comment by RSSchermer** [comment]
How many items are we talking about? What Ember version?

**Comment by medokin** [comment]
Ember 2.3.0-beta.3 and about 1000 items, partially hidden in accordions.
If I click the checkbox, the page is blocked, and responses after a few seconds.

**Comment by RSSchermer** [comment]
Thanks! I'll try to reproduce some time in the next couple of days and see if I can profile it and find out if the bottleneck is somewhere in this addon's code or in Ember's rendering engine.

Current best guess is that updating the selection trigger's a redraw of the entire `multiselect-checkboxes` component, which in this case means redrawing 1000 checkboxes, which I can see being somewhat heavy on the rendering engine. 

If this is indeed the case, then I don't think this can be addressed in this addon. The only solution in this case may be to split it across multiple `multiselect-checkboxes` components, each with its own selection. In this case a change in the selection for one of these `multiselect-checkboxes` only requires the engine to redraw the checkboxes in that specific component.

**Comment by RSSchermer** [comment]
As of 0.6.1 a change to the selection should no longer cause a rerender of all checkboxes. In my tests this greatly improved the response time after checking a checkbox with a large number of checkboxes (1000). Let me know if this fixes your issue, I'd be happy to reopen if the problem persists.
