### ISSUE TITLE
Ember 1.12 support?

### ISSUE THREAD

**Issue by FredUK** [RSSchermer/ember-multiselect-checkboxes#26]
Hi there, first of all thanks for the great plugin which replaces the lack of support of the native checkbox.

I'm trying to use this on a project with Ember 1.12 (did not have a chance to upgrade yet) and it appears that when I use ```onchange=(action 'listChanged')``` it throws an error saying ```Cannot read property 'setAttribute of undefined```

In Ember 1.12 and it's components we do not use onchange=(action 'actionName') . We simply use onchange='listChanged' (action name), however this does not work because it seems the code is calling ```functionName()``` instead of using the sendAction ( https://github.com/RSSchermer/ember-multiselect-checkboxes/blob/master/addon/components/multiselect-checkboxes.js#L29 ) .

Do you have any thoughts on how I could use this with 1.12 and fix this problem with the action?

Bedankt en groetjes :+1:

**Comment by RSSchermer** [comment]
Hey, thanks for bringing this up.

I can't give you a solution off hand. I think we'd have to support both passing a string and a function to handle this. However, I'm not sure how well that would play with the current and future versions of Ember. Although it would of course be nice to support older versions of Ember as much as possible, supporting the current (and future) version as best as possible takes priority.

I'll have to investigate and experiment a bit. You've caught me at a somewhat busy time, so please bear with me for a bit (feel free to bump this in a couple of days though if I haven't come back to this). If this doesn't pan out, I could still always create a separate 1.12 branch that supports this for you. I wouldn't be supporting and updating that branch as this addon evolves further, but it should cover you're use case for now, untill hopefully some day you'll be to upgrade to Ember 2.x.

**Comment by RSSchermer** [comment]
It has been a while, my apologies. It has been a busy time for me and this fell of my radar.

Is this still an issue for you? It occurred to me that depending on what your use case is, you might be able to use an observer on your selection property. Something like this:

```js
// some-controller.js
import Ember from 'ember';

export default Ember.Controller.extend({  
  mySelection: [],
  
  selectionChanged: Ember.observer('mySelection', function () {
    let selection = this.get('mySelection');

    // Do something with the selection
  })
});
```

If this doesn't work for your use case, I'll see about setting up a 1.12 branch.

**Comment by RSSchermer** [comment]
Closing for now. Feel free to reopen if this issue persists.

**Comment by hferinf** [comment]
We upgraded ember to the latest and we now get:

vendor.js:30409 Assertion Failed: You modified "activeNotifications" twice on <foo:header-block::ember761> in a single render. It was rendered in "component:section-header-block" and modified in "component:multiselect-checkboxes". This was unreliable and slow in Ember 1.x and is no longer supported. See https://github.com/emberjs/ember.js/issues/13948 for more details.
Error
