### ISSUE TITLE
ember multi-select checkbox

### ISSUE THREAD

**Issue by nandhiniG** [RSSchermer/ember-multiselect-checkboxes#28]
hi,

**Comment by nandhiniG** [comment]
how to add images as options in this checkbox addon

**Comment by RSSchermer** [comment]
Hi @nandhiniG 

If I'm understanding you correctly, you should probably use a custom template block to achieve this.

Perhaps something like:

```hbs
{{#multiselect-checkboxes options=images selection=selectedImages as |imageOption isSelected|}}
  <li>
    <label>
      {{input type="checkbox" checked=isSelected}}
      <img src="{{imageOption.src}}">
    </label>
  </li>
{{/multiselect-checkboxes}}
```

Does that help?

**Comment by RSSchermer** [comment]
Closing for now. If my suggestion above did not address your use case, feel free to reopen.
