### ISSUE TITLE
Please include expected sample data in users in documentation

### ISSUE THREAD

**Issue by poudelprakash** [RSSchermer/ember-multiselect-checkboxes#30]

**Comment by RSSchermer** [comment]
Do you mean an example of the kinds of values that can be bound to the `options` attribute?

The readme currently says: "This component can be used with an array of primitives as the options, an array of plain javascript objects as the options, or an array of Ember objects as the options."

Not sure how to go about providing examples for each case though. There's a combined example in the [demo source code](https://github.com/RSSchermer/ember-multiselect-checkboxes/blob/ea1df08a373ddf092f6c9622587ed2aa92abab61/demo-app/app/controllers/application.js), perhaps this is sufficient. I think providing separate examples for each case in the readme might be a little verbose.

**Comment by poudelprakash** [comment]
I would prefer examples in readme on anyday.

I had to search for demo repo and see the example.
Linking demo repo's code directly in readme will be good option too..anything that saves developer's time would be great.

**Comment by RSSchermer** [comment]
How about [this](https://github.com/RSSchermer/ember-multiselect-checkboxes/pull/31/files)?

**Comment by poudelprakash** [comment]
:+1:

**Comment by RSSchermer** [comment]
Merging... Thanks for bringing this up!
