### ISSUE TITLE
Promise-aware?

### ISSUE THREAD

**Issue by wilsonohyeah** [RSSchermer/ember-multiselect-checkboxes#32]
Do you have any plans to make this component promise-aware in regard to the `options` that are passed in?

**Comment by RSSchermer** [comment]
I did not, and I think perhaps that's not actually necessary. Have you looked into [PromiseObject](http://emberjs.com/api/data/classes/DS.PromiseObject.html) and [PromiseArray](http://emberjs.com/api/data/classes/DS.PromiseArray.html)? This is also what Ember Data uses to represent association values (`hasOne` and `hasMany` respectively). I think they might cover most use-cases. I guess the important question is though, would they cover yours?

**Comment by RSSchermer** [comment]
Closing for now. Feel free to reopen if this issue persists.
