### ISSUE TITLE
multiselect-checkboxes with template does not render the checkbox itself

### ISSUE THREAD

**Issue by fr0gs** [RSSchermer/ember-multiselect-checkboxes#37]
Hello,

I want to customize a checkbox list where you have different behavior when clicking the checkboxes or clicking the labels itselves.

```
{{#multiselect-checkboxes options=searchResults selection=clickedResults as |result|}}
    <li>
        <button {{action 'listItemClick' result}}>
            {{await result.defaultPrefLabel}}
              {{#if result.defaultCode}} - {{result.defaultCode}}{{/if}}
        </button>
    </li>
{{/multiselect-checkboxes}}
```

But in the rendered html the `<input type="checkbox">` never appears, although my labels appear correctly. and they react to the listItemClick action. 
I am using Ember **2.3.0** for this project

**Comment by fr0gs** [comment]
Ok it seems that for this case I needed to add explicitly the checkbox to inside the list

**Comment by RSSchermer** [comment]
Yes, you have to add the html for a checkbox input to the template. Something like this should work:

```hbs

{{#multiselect-checkboxes options=searchResults selection=clickedResults as |result isSelected|}}
    <li>
        {{input type="checkbox" checked=isSelected}}

        <button {{action 'listItemClick' result}}>
            {{await result.defaultPrefLabel}}
              {{#if result.defaultCode}} - {{result.defaultCode}}{{/if}}
        </button>
    </li>  
{{/multiselect-checkboxes}}
```

**Comment by RSSchermer** [comment]
Closing for now. Feel free to reopen if this is still an issue.
