### ISSUE TITLE
adding a click action handler

### ISSUE THREAD

**Issue by SirZach** [RSSchermer/ember-multiselect-checkboxes#4]
Just wanted to throw out there that it would be useful to be able to pass along a click action up to a controller. If I have the select boxes updating a <code>hasMany</code> relationship, I might want to save upon checking/unchecking each checkbox. Right now, you would have to set up an observer on that relationship instead of just having an action fired from the component.

Maybe something like
```javascript
{{multiselect-checkboxes
    action='saveColumnChanges'
    labelProperty='propertyName'
    options=columnGroup.results
    selection=controllers.application.model.inventoryTable
}}
```

**Comment by RSSchermer** [comment]
That's a good idea. I think it should probably pass the new selection as an argument to the handler function. I'll look into it when I have time in a couple of days :+1:

**Comment by RSSchermer** [comment]
Closing this for now. I think being able to pass a custom block as of 0.4.x should address this, as discussed in #5. If there are still issues I'd be happy to reopen the issue.

**Comment by jfelchner** [comment]
@RSSchermer yes, I believe there are still issues with this.  The block works great, but the action gets sent _before_ the `selection` computed property is updated.  So if you want to do anything with the changes selections in the action, you can't do that (or I'm too ignorant to know how).

**Comment by RSSchermer** [comment]
I think one thing we can do is pass the value as a third block param:

```hbs
{{#multiselect-checkboxes options=users labelProperty='name' selection=selectedUsers as |label isSelected value|}}
  <li>
    <label {{action 'itemchanged' value isSelected}}>
      {{input type="checkbox" checked=isSelected}}
      {{label}}
    </label>
  </li>
{{/multiselect-checkboxes}}
```

Perhaps that would be enough to fix your use-case.

I can't think of a way at the moment to actually change the order in which the actions fire and make the selection change happen before the click event is triggered. The only thing I can think of that might work is a bit of a hack:

```js
actions: {
  itemChanged: function () { // Event handler
    Ember.run.later(() => {
      // actual handler
    }, 0); // Push the actual handler onto the bottom of the event queue
  }
}
```

I haven't tested that yet (I think you might have to bind `this` to the "actual handler" function).

**Comment by RSSchermer** [comment]
@jfelchner Did either of my suggestions resolve your issue or does this remain a problem?

**Comment by RSSchermer** [comment]
As suggested by @nadnoslen in #18, passing the option directly instead of passing the option label and option value should allow more flexibility. Therefore, as of 0.6.0 my upthread example should be replaced with:

```handlebars
{{#multiselect-checkboxes options=users selection=selectedUsers as |user isSelected|}}
  <li>
    <label>
      {{input type="checkbox" checked=isSelected}}
      {{user.name}}
    </label>
  </li>
{{/multiselect-checkboxes}}
```

See change log for more details.

Closing this again for now. Would be very happy to reopen once again if this issue still persists.
