### ISSUE TITLE
Don't know where else to say it, so thanks!

### ISSUE THREAD

**Issue by michaellee** [RSSchermer/ember-multiselect-checkboxes#44]
Just wanted to say Roland @RSSchermer thanks very much for this ember addon. I've been using it this week for a project and it is awesome. Not only that, but the documentation is top notch! Sorry for muddying up your issues, but didn't see any other contact information. Cheers!

**Comment by RSSchermer** [comment]
Hey, that's actually so nice of you to say! Thanks you very much! It's not all just me though, I've had some excellent contributions. Hope using this addon continues to be a good UX for you!
