### ISSUE TITLE
setting default values from hasMany 

### ISSUE THREAD

**Issue by dbinetti** [RSSchermer/ember-multiselect-checkboxes#47]
I'm using the multi-select to populate a hasMany field on my model.  I've got the adding and removing portion done and works flawlessly, great!  

However, I can't figure out how to populate the initial `selected` with the values that already exist on the model.  So if I add, the checkboxes all show exactly properly.  However, if I refresh, the data are still in the database but the multiselect shows empty.  I'm sure I'm missing something trivially simple, but in any case have to ask to be sure.  What is the proper patter to set the initial values from the database?

**Comment by RSSchermer** [comment]
It might be a typo, but the attribute you should bind your selection to is called `selection` rather than `selected`.

However, assuming that this is a typo and you are indeed binding to `selection`, then it's hard to give a specific answer without seeing code I'm afraid. In general, you should be able to just bind an ember-data `hasMany` property to the `selected` attribute and have it just work. Did you check the network traffic on a new page load to see if your application ends up making the proper database request to fetch the data for the `hasMany` in question?

> What is the proper patter to set the initial values from the database?

I think the proper place for any kind setup of values from a database on page load is on the `Route` object for the page.  In this case you may want to try doing your setup in the [setupController](http://emberjs.com/api/classes/Ember.Route.html#method_setupController) hook:

```js
// app/routes/my-route.js
import Ember from 'ember';

export default Ember.Route.extend({
  setupController(controller, model) {
    controller.setProperties({
      model: model,
      mySelection: .... // e.g. model.get('someHasManyProperty')
    });
  }
});
```

Then bind `mySelection` to the `selection` attribute.

**Comment by dbinetti** [comment]
thank you for your response; I apologize for filing an issue when it's
clear the problem is my lack of understanding with ember.  I have started
employing some of your suggestions; haven't had success yet (promises are
so hard to deal with) but am making more progress than I had before.  I
just thought this would be a common use case and there would be a specific
example to which you could direct me.

**Comment by dbinetti** [comment]
So I've tried for a while and still can't make it work.  However, I also realize I've been leaving out a fairly important piece of the puzzle.  So let me explain more fully (with some code and pseudo code.)

The important architectural piece is that I'm trying to use the mutiselect to build a join entry.  Specifically, assume that one model is a `Person` who wants to enter one or more `Contest`s.  When that person enters a contest, a `Contestant` record is created, which represents that the person has entered a particular contest.  

So I'm building the multiselect on a route whose model represents the person.  Then, I'm presenting the `options` as `contestOptions`, which is an array of the contests available to that person.  Then, when the user clicks on each `contest`, a `contestant` record is created when the box is checked, and it is destroyed when the box is unchecked.  For the purposes of this question, you may assume that the `contestant` model simply contains two fields: a `belongsTo` `contest` and `belongsTo` `person`.

So what I'm trying to achieve is that the initial `selection` value represents an array of the contests that belongTo the contestants on the person.  If, for instance, I set up a computed property on the person model as:
```
selectedContests: Ember.computed.mapBy(
    'contestants',
    'contest'
)
```

I will get back an array that essentially reflects the subset of the contests which populate the `options` field.  So how do I get those checkboxes to reflect that?  

Thanks for your patience....

**Comment by RSSchermer** [comment]
I see. Were you able to get the initial display of the `selection` working correctly with something like `setupController`?

The issue here is that `selectedContests` isn't really a magic Ember-Data `many` collection anymore, its just a plain collection of `Contest` instances. Therefore adding another `Contest` to a `Person`'s `selectedContests` is not going to trigger any Ember-Data magic and create a new `Contestant` instance for you. 

Do you want it to create and persist new `Contestant` instances as soon as a checkbox is checked or unchecked? In that case you could something along these lines with the `onchange` hook:

```hbs
{{multiselect-checkboxes options=contests selection=model.selectedContests onchange=(action 'updateSelectedContests') labelProperty='name'}}
```

```js
// controller.js
import Ember from 'ember';

const { Controller } = Ember;

export default Controller.extend({
  ...

  actions: {
    updateSelectedContests(newSelection, value, operation) {
      this.set('model.selectedContests', newSelection);
     
      if (operation == 'added') {
        this.get('store').createRecord('contestant', { person: model, contest: value });
      } else if (operation == 'removed') {
        model.get('contestants').find((c) => c.get('contestId') === value.get('id')).destroyRecord();
      }
    }
  }
});
```

**Comment by dbinetti** [comment]
Right, so I have that last part working -- adding and removing `Contestant` objects works flawlessly, thank you.  

The issue is the first one -- I can't get the initial display of the `selection` to work, either with `setupController` or populating with a computed property in the actual controller or on the model or in any other way I've tried.  

The very first time I load a clean record, it's perfect.  All the options are unchecked, and if I check and uncheck `Contestant` objects are added and removed perfectly.  But, say I check one -- adding a `Contestant` record -- and then refresh the page.  Now all boxes are unchecked, even though a `Contestant` record exists for that `Person`.  If I try to check things now, then it tries to add a record that is already there and the problems obviously begin.

It's all coming down to:  how do I get the `selection` to reflect the current state when using related records?  My project is open source; the template is [here](https://github.com/dbinetti/barberscore-ember/blob/master/app/templates/admin/quartet-manager/quartet/registrations/registration.hbs#L127) and the controller is [here](https://github.com/dbinetti/barberscore-ember/blob/master/app/controllers/admin/quartet-manager/quartet/registrations/registration.js#L42)

**Comment by dbinetti** [comment]
Actually, I think I can share most of the relevant bits here:

Consider these three models:

```
// Person
export default Model.extend({
  name: attr('string'),
  contestants: hasMany('contestant', {async: true}),
});

// Contest
export default Model.extend({
  name: attr('string'),
  contestants: hasMany('contestant', {async: true}),
});

// Contestant
export default Model.extend({
  name: attr('string'),
  contest: belongsTo('contest', {async: true}),
  person: belongsTo('person', {async: true}),
});
```

Then, given this `multiselect` on a template backed by a `Person` model:

```
    {{multiselect-checkboxes
      options=contestOptions
      labelProperty='name'
      selection=selectedContests
      updateSelectionValue=true
      onchange=(action "updateSelection")
    }}
```

The `contestOptions` for that multiselect represents an array of `Contest`s selected by some set of criteria.  The `selectedContests` represents the `Contestant` objects related to the the `Person`.  The `updateSelection` action adds and removes `Contestant` objects accordingly.  

With that schema, I don't know how to set up `selectedContests` such that on refresh it reflects the persisted state.

**Comment by RSSchermer** [comment]
> Right, so I have that last part working -- adding and removing Contestant objects works flawlessly, thank you.

Good to hear!

I think that what you may in fact want is to load multiple "models" on your route as described [here](https://guides.emberjs.com/v2.12.0/routing/specifying-a-routes-model/#toc_multiple-models). You could try something like this as your route:

```js
// app/routes/admin/quartet-manager/quartet/registrations/registration.js

export default Ember.Route.extend(AuthenticatedRouteMixin, {
  model(params) {
    return RSVP.hash({
      performer: this.get('store').findRecord('performer', params.performer_id),
      selectedContests: this.get('store').query('contestants', {
        filter: {
          performer_id: params.performer_id
        },
        include: 'contest'
      }).then(function (contestants) {
        return contestants.mapBy('contest')
      })    
    });
  }
});
```

This assumes your JSONAPI backend supports filtering and including (and I haven't tested it so you may have to tweak it a little).

You'll have to make some adjustments to your controller and template to account for the fact that `model` is now a hash (I'd add a computed `performer` property that aliases to `model.performer` and a computed `selectedContests` property that aliases to `model.selectedContests`).

**Comment by dbinetti** [comment]
Thank you for being so willing to help (and for your patience.)

So I see where you're going with this, but it feels like overkill.  I can access what are affectively the `selectedContests` through a simple computed property.  For instance, this CP on the `Performer` (nigh `Person`) model:

```
  selCons: computed(
    'contestants.@each.contest', function() {
      return this.get('contestants').mapBy('contest');
  })
```

returns the proper array on each page load. That's the data I need; how do I put it to use?

I should note that it returns a promise, since the related records are async -- perhaps that's related?

**Comment by RSSchermer** [comment]
If that does indeed return a plain promise rather than a [PromiseArray](https://emberjs.com/api/data/classes/DS.PromiseArray.html) or a [PromiseManyArray](https://emberjs.com/api/data/classes/DS.PromiseManyArray.html), could you try wrapping that promise in a `PromiseArray`:

```js
selCons: computed('contestants.@each.contest', function() {
  return DS.PromiseArray.create({
    promise: this.get('contestants').mapBy('contest')
  });
})
```

**Comment by dbinetti** [comment]
How would I tell whether or not it's a promise or ember promise?

I believe it's an Ember promise; it appears to have methods unique to that object.  Regardless, I tried the wrapped approach as you suggested and that isn't working either...

**Comment by dbinetti** [comment]
Just checking in to see if there's anything else I can do to help test this.

**Comment by RSSchermer** [comment]
I have one last idea, try:

```js
selCons: computed('contestants.@each.contest', function() {
  return DS.PromiseArray.create({
    promise: this.get('contestants').then(function (contestants) { 
      return contestants.mapBy('contest'); 
    })
  });
})
```

It might be that calling `mapBy` on the promise before it has resolved is whats causing the problem here.

**Comment by dbinetti** [comment]
Forgive me, but I'm asking a different question.  I believe I might be missing something fundamental. 

On the multiselect template, the `options` refers to `contestOptions`, which is a list of `contest` objects, and that renders the superset list of options within the `multiselect` component perfectly.  . Then, on that same template right next to the component, I can render to the page a list of `selectedContestsCP` which is an array of the `contest` objects that related to this performer.  Specifically, `selectedContestsCP` is a subset of `contestOptions` that I'm building  through a computed property on the `performer` model.  The items in the `selectedContestsCP ` is what I'm trying to get reflected in the component.

So, now that I have the data I need, how do I get it into the `multiselect` component itself?  Merely setting `selection` to `selectedContestsCP` does not work (and by 'work' I mean rendering checked boxes for those items that are present on `selectedContestsCP` when the page is loaded.  I've toggled the `updateSelectionValue` but that does not change things one way or another.  So how do I get the component to realize "ah, the items in this array are already in my options array; I should check those boxes to reflect state accordingly."

Sorry to be so verbose, but I just want to make sure I'm not missing anything....

**Comment by RSSchermer** [comment]
Ordinarily just setting `selection` to `selectedContestCP` should work. I realize now however, that the problem might be that for some reason you're not getting the same instances from the Ember-Data `store` for both cases and it is therefore not recognizing that they are the same objects.

If that's the case, then it should work if we'd use IDs rather than objects as the values: using `mapBy` with `contestId` rather then `contest` and then setting `valueProperty='id'` on the `multiselect-checkboxes`.

**Comment by dbinetti** [comment]
Sadly, no.

<img width="571" alt="screen shot 2017-04-03 at 2 33 45 pm" src="https://cloud.githubusercontent.com/assets/161722/24632864/a83a261c-187a-11e7-9c64-0cc5da25553f.png">

**Comment by dbinetti** [comment]
Belay that -- it worked!  I misread and did  `labelProperty`.  But when I changed it to `valueProperty` it worked properly.  Glory, Hallelujah!  

Whew -- thanks for your diligence in tracking it down.  I'll keep poking around to see if the functionality works with everything else.  **THANKS**

**Comment by dbinetti** [comment]
Yep, flawless.  Awesome.  Closing

**Comment by RSSchermer** [comment]
Good to hear!
