### ISSUE TITLE
Please upgrade ember-cli-babel to ^6.0.0

### ISSUE THREAD

**Issue by thomblake** [RSSchermer/ember-multiselect-checkboxes#52]
Outdated ember-cli-babel depends on outdated ember-cli-version-checker, which causes the deprecation warning noted here: ember-cli/ember-cli-version-checker#48 (amongst other reasons)

**Comment by RSSchermer** [comment]
Should be resolved as of v 0.11.0, let me know if you still run into problems.

**Comment by thomblake** [comment]
Thanks!

**Comment by wukongrita** [comment]
Hi, I have the same issue:

```
$ ember install ember-multiselect-checkboxes
NPM: Installed ember-multiselect-checkboxes
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade toat least ember-cli-babel 6.6.0
Installed addon package.
```

```
$ ember -v
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade toat least ember-cli-babel 6.6.0
ember-cli: 2.16.2
node: 8.9.4
os: darwin x64
```

There is no warning, if i uninstall the ember-multiselect-checkboxes; any help? thx

**Comment by RSSchermer** [comment]
Could you try 0.11.1?

**Comment by wukongrita** [comment]
@RSSchermer Thank you, 0.11.1 works for me... 👍
