### ISSUE TITLE
Binding from Query Params

### ISSUE THREAD

**Issue by jfelchner** [RSSchermer/ember-multiselect-checkboxes#8]
When binding to/from query params, typically you're only working with the `id` of the items that you want to check, not the objects themselves.  It'd be nice if you could pass something into the component which understood that.  Maybe `selectedIds`?

**Comment by RSSchermer** [comment]
Hmm, perhaps a `valueProperty` attribute, in the same vein as the `labelProperty` attribute?

Then you could set `valueProperty="id"` and just pass the ids into `selection`. The flipside to that though, is that you also get ids back from `selection`, not whole objects. I guess whats you'd want though.

Curious to hear what you think!

**Comment by jfelchner** [comment]
@RSSchermer absolutely.  I think that'd work great actually!

**Comment by RSSchermer** [comment]
Ok, I'll look into it some time this week.

**Comment by RSSchermer** [comment]
Hey sorry for the delay.

It *should* work in 0.3.x, let me know if you run into any problems.

**Comment by jfelchner** [comment]
Awesome! I'll give it a try! Thanks!

**Comment by rizkysyazuli** [comment]
I'm really sorry for off-topic. But i wanted to know how @jfelchner did your query param. My URLs keep getting mangled by Ember.

```js
// app/components/article/filter-category.js
export default Ember.Component.extend({
  routing: Ember.inject.service('-routing'),

  selectedCategory: [],

  actions: {
    filterCategory(newSelection, value, operation) {
      // expected value: 1,2,3,..
      let selected = newSelection.join(',');

      // any idea why when injected into URL, the value gets escaped
      // like this: /parenting?category_id=3%2C2
      this.get('routing').transitionTo('parenting', [], { category_id: selected });
    }
  }
});
```
