### ISSUE TITLE
Multiselect Checkbox Option example

### ISSUE THREAD

**Issue by joshhornby** [RSSchermer/ember-multiselect-checkboxes#9]
Have you got an example of how to use the multiselect-checkbox-option? 

Thanks

**Comment by RSSchermer** [comment]
`multiselect-checkbox-option` was really meant to be part of the public api, I consider it just an implementation detail. There's a refactor coming soon which should give you much more room to customize your option list (see #5). That refactor will make `multiselect-checkbox-option` obsolete.
